INSERT INTO TBL_USER
    (NUM, EMAIL, PASSWORD, NICKNAME, PHONE, ADDRESS, PROFILE_FILE_NAME, PROFILE_UPLOAD_PATH, POINT, REGIST_DATE)
    VALUES(SEQ_USER.NEXTVAL, '', '', '', '', '', '', '', 0, SYSDATE);
   
INSERT INTO TBL_USER
    (NUM, EMAIL, PASSWORD, NICKNAME, PHONE, ADDRESS, PROFILE_FILE_NAME, PROFILE_UPLOAD_PATH, REGIST_DATE)
    VALUES(SEQ_USER.NEXTVAL, 'ddd', 'dddd', 'dddd', 'dddd', '', '', '', SYSDATE);
    
SELECT *
FROM TBL_USER;
   
UPDATE TBL_USER
SET EMAIL='', PASSWORD='', NICKNAME='', PHONE='', ADDRESS='', PROFILE_FILE_NAME='', PROFILE_UPLOAD_PATH='', POINT=0, REGIST_DATE=SYSDATE
WHERE NUM=0;




INSERT INTO TBL_ORDER
(NUM, TOTAL, COUNTING, REGIST_DATE, PRODUCT_NUM, USER_NUM, STATUS)
VALUES(SEQ_ORDER.NEXTVAL, 1000, 10, SYSDATE, 1, 1, '1' );


INSERT INTO TBL_PRODUCT
(NUM, NAME, CONTENT, CATEGORY, PRICE, STOCK, ORIGIN, MANUFACTURER, SUPPLIER, REGIST_DATE)
VALUES(SEQ_PRODUCT.NEXTVAL, '민지수', '해', '생활', 1000, 10, '호주', '짱꺠', '삼성',SYSDATE);
